spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/fileupload
    username: admin
    password: test1234

server:
  tomcat:
    max-http-form-post-size: 500MB
